Publish the commands sent towards the controllers after the limits
project-march/hardware-interface pull request #116
Opened 2019-07-23 15:29 UTC by JitskedeVries

In combination with this pullrequest: https://github.com/project-march/march-iv/pull/288, the commands that are adjusted by the limitinterface are published onto a topic. 

More explanation about why we want to publish this can be found in that pull request.

2019-07-24 10:06 UTC, sopje reviewed
It worked on the rotational test joint, please take a look at my small comment

2019-07-24 10:06 UTC, sopje commented on march_hardware_interface/src/march_hardware_interface.cpp
> +  ROS_DEBUG("Before limits: Trying to actuate joint %s, to %lf "
don't you want this not loop through all the joints like the after limits ROS_debug message?

2019-07-31 10:00 UTC, Ishadijcks requested changes

2019-07-31 10:00 UTC, Ishadijcks commented on march_hardware_interface/src/march_hardware_interface.cpp
> +      after_limit_joint_command_pub_->msg_.effort_command.push_back(0);
This should be moved to another method instead of cluttering the read method

2019-07-31 13:47 UTC, Ishadijcks requested changes
I don't understand why there are so many changes in this pr.
It looks like many refactors have been merge since you've branched from develop. Can you either merge develop into it and clean it up, create a new branch from the current develop with your changes

2019-07-31 13:47 UTC, Ishadijcks commented on march_hardware_interface/src/march_hardware_interface.cpp
> +          this->nh_, "/march/after_limit_joint_command/", 4));
Please pick a topic closer related to the controller.

2019-07-31 13:47 UTC, Ishadijcks commented on march_hardware_interface/src/march_hardware_interface.cpp
> +        }
Please refactor this to use the style develop uses at the moment.
```
march4cpp::Joint joint = marchRobot.getJoint(joint_names_[i]);
```
Once and use the variable later

2019-07-31 14:53 UTC, JitskedeVries commented
> I don't understand why there are so many changes in this pr.
> It looks like many refactors have been merge since you've branched from develop. Can you either merge develop into it and clean it up, create a new branch from the current develop with your changes

It is kind of weird indeed. Will do this!

2019-08-01 09:42 UTC, closed without merging