Refactor/two slaves
project-march/hardware-interface pull request #15
Opened 2019-02-12 10:02 UTC by martijnvandermarel

WIP - feedback request
Closes #13 
Closes #9 

Can be tested with a DieBieSlave with TemplateGES firmware (see github.com/project-march/ethercat-slaves) and rqt to publish LED commands on topic march/template/data with a Uint8 std_msg.

ifname in launch file may need to be changed depending on your hardware (type ifconfig in terminal to find yours).

Files to be refactored before merge:
ethercat_safety (.cpp/.h)
ethercat_io (.cpp/.h)

2019-02-12 11:36 UTC, Ishadijcks requested changes
## In advance
I am very critical in this review, and that some of my critique is directed towards code that you haven't written yourself. I understand that this can feel a bit unfair as it is not your fault at all. However I won't leave out remarks because of this as I don't want to end up in the same situation as last year.

## Main points
- The soem library is copied into the project instead of properly included as a dependency, this won't allow us to update soem and is generally a bad way to include a library.
- Use [ROS logging](http://wiki.ros.org/roscpp/Overview/Logging) tools as they are so much better than simple prints.
- Specify your TODO's, don't just claim 'refactor in the future' but say what needs to change and why.
- The OOP logic behind the slaves can be optimized a lot to avoid using long if/elses for each type of slave. This is sort of advanced and I'd like to discuss it in person.
- Improved failure detection. Checking for 20 errors and then saying, 'welp I guess something went wrong' leads to frustrating debugging session.


Anyway, I hope this review motivates you enough to implement these features. Or if you want to yell at how mean it was you know where my office is :)

2019-02-12 11:36 UTC, Ishadijcks commented on custom_msgs/package.xml
> +    <description>Developer input device to send commands to the march-iv</description>
Is it?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  printf("Starting ethercat\n");
Use ROS debugs instead of prints

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  printf("ec_init on %s succeeded.\n", ifname.c_str());
Use ROS debugs instead of prints

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  // Todo: Change to 0
When will this be done?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +    if (slaveList[j]->getType() == "IMC")
Why have a single slavelist if you are checking its type on access?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  printf("segments : %d : %d %d %d %d\n", ec_group[0].nsegments, ec_group[0].IOsegment[0], ec_group[0].IOsegment[1],
Use ROS debugs instead of prints

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  } while (chk-- && (ec_slave[0].state != EC_STATE_OPERATIONAL));
If you know this will run a max of 40 times, consider replacing it with a for loop that can break early

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +    }
This can be done better with OOP techniques, please come by to discuss.

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.cpp
> +  ethercat_safety::monitor_slave_connection();
To what? Will you know what this means in a week? In a month?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatMaster.h
> +  int expectedWKC;     // Expected working counter
Unclear variable name and case

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/EthercatNode.cpp
> +std::vector<Slave*> initSlaves(ros::NodeHandle nh)
Replace with factorypattern

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/IMC.cpp
> +  printf(success ? "true\n" : "false\n");
Extremely ambiguous as to where the error happened or what the error is.
Can you think of a way to refactor this so we know which of the 25 `sdo_bit16()` calls throws an error?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/IMC.cpp
> +IMC::IMC(std::string name, uint16 number) : Slave(name, number)
Number? What does that mean? Count? Index?
I can see it's a number by its type.

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/Slave.cpp
> +Slave::Slave(std::string name, uint16 number)
What is the purpose of different classes if we are going to refer to them by their type at all times?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/TemplateGES.cpp
> +  //  printf("Set LED\n");
Commented code

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/TemplateGES.cpp
> +  // For now, publish by printing in terminal
Add a todo, document what's wrong and how it will be refactored in the future.

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_SDO.cpp
> +}
```
int sdo_bit(int slave, uint32_t index, uint8_t sub, uint32_t value, int bits)
{
  return ec_SDOwrite(slave, index, sub, FALSE, bits, &value, EC_TIMEOUTRXM);
}
```

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_io.cpp
> +  data_ptr += module_index * 8; // Probably wrong!
This line alone is worth a rejection

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_io.cpp
> +}
I have a feeling that this entire file can be refactored in two methods with the same functionality.

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_io.cpp
> +  /* Set or Clear bit */
Maybe call the method `set_or_clear_output_bit()`?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_io.h
> +#endif  // ETHERCAT_IO_
This file should be abstracted as soon as possible

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_safety.cpp
> +  // Todo: Fix this
Is commenting it out fixing it?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_safety.cpp
> +int ethercat_safety::are_slaves_disconnected()
Expected to return a boolean with this name

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/ethercat_safety.cpp
> +  if (lostSlaveIndex || prevLostSlaveIndex)
Why check the `prevLostSlaveIndex`?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/launch/march_ethercat.launch
> +            ifname: 'enp4s0f2'
Is there a way to detect this ifname dynamically?

2019-02-12 11:36 UTC, Ishadijcks commented on march_ethercat/launch/march_ethercat.launch
> +            testGES: TEMPLATEGES
Why is this a launch parameter, is it expected to change with certain launches?

2019-02-12 14:56 UTC, TimBuckers requested changes

2019-02-12 14:56 UTC, TimBuckers commented on march_ethercat/Slave.cpp
> +// Base class source for all slaves
create a folder for all slave objects, this makes the package more structured

2019-03-06 10:59 UTC, Ishadijcks commented
Made obsolete by #16

2019-03-06 10:59 UTC, closed without merging