Fix/pm 196 fix return value initation imc check
project-march/hardware-interface pull request #188
Opened 2019-12-13 10:37 UTC by JorisWeeda

Closes PM-196

## Description
When initiating the IMC with different SDO-messages the return value is the workingcounter of the SDO. Currently the program does a bitwise-and with a boolean which states the succes variable. The working counter could be an even number which results in the ROS_ASSERT_MSG being initiated. This is changed to checking if the return value is 0, this is the error statement and the program will raise an error. 

## Changes
* Removed the succes boolean from the initiation of the IMC
* Added a check if the working counter is 0 in the SDO write functions

2019-12-13 13:11 UTC, Roelemans submitted a review, later dismissed
Looks good! Has this been tested? Does it improve things?

2019-12-13 14:13 UTC, RutgerVanBeek submitted a review, later dismissed
Nice work. Of course test on exo first

2019-12-14 16:02 UTC, Olavhaasie requested changes

2019-12-14 16:02 UTC, Olavhaasie commented on march_hardware/src/EtherCAT/EthercatSDO.cpp
> +int ReceivedWorkingCounter;
You don't have to use a global variable here, since you only use it local in the methods

2019-12-17 13:55 UTC, Olavhaasie approved these changes

2019-12-18 18:26 UTC, Olavhaasie commented
Closed since this fix returns errors from the sdo writes. Will be looked at in PM-229

2019-12-18 18:26 UTC, closed without merging