Replace obscure smoothing method normal logic
project-march/hardware-interface pull request #226
Opened 2020-03-04 13:44 UTC by Roelemans

Replace obscure smoothing method with simple math that does exactly the same.

2020-03-04 14:00 UTC, Olavhaasie requested changes
You should also remove the `control_toolbox` dependencies in https://github.com/project-march/hardware-interface/blob/07046a4ae05ecc41d8cd65fe57ab2f0f40d3aac2/march_hardware_interface/CMakeLists.txt#L7 and https://github.com/project-march/hardware-interface/blob/07046a4ae05ecc41d8cd65fe57ab2f0f40d3aac2/march_hardware_interface/package.xml#L20

If we ever want to use them again, we can simply revert them, better to remove it to avoid cluttering the dependencies if we forget to remove it later.

2020-03-04 14:00 UTC, Olavhaasie commented on march_hardware_interface/src/march_hardware_interface.cpp
> +    joint_velocity_[i] = 0.2 * joint_velocity + 0.8 * joint_velocity_[i];
It think it's better to use a constant here declared in `MarchHardwareInterface` something like
```c++
public:
...
static constexpr double ALPHA = 0.2;
...
```
Then change this line to
```suggestion
    joint_velocity_[i] = MarchHardwareInterface::ALPHA * joint_velocity + (1 - MarchHardwareInterface:ALPHA) * joint_velocity_[i];
```

2020-03-04 15:50 UTC, Olavhaasie approved these changes

2020-03-05 13:44 UTC, RutgerVanBeek approved these changes

2020-03-05 13:55 UTC, merged