Check for change in voltage and encoder positions
project-march/hardware-interface pull request #250
Opened 2020-04-03 09:06 UTC by Roelemans

## Description

I made the naïve assumption that imc voltage would always change. I forgot that imc voltage, is contained in 16 bits and therefore highly discrete. So instead, we should check if any of imc voltage, or the encoders have updated.

## Changes

* Check whether either voltage or one of the encoders has updated instead of voltage alone.

2020-04-03 09:47 UTC, Olavhaasie requested changes

2020-04-03 09:47 UTC, Olavhaasie commented on march_hardware/include/march_hardware/Joint.h
> +  double previous_incremental_position = 0.0;
:see_no_evil: 
```suggestion
  double previous_absolute_position_ = 0.0;
  double previous_incremental_position_ = 0.0;
```

2020-04-03 10:18 UTC, Roelemans commented on march_hardware/include/march_hardware/Joint.h
> +  double previous_incremental_position = 0.0;
Oopsie

2020-04-06 09:45 UTC, Olavhaasie submitted a review, later dismissed

2020-04-06 10:34 UTC, RutgerVanBeek requested changes
You still have a chance (although small) of false positives with this technique. It seems that the current  the most unique values. Therefore I think you should at least include the current in the test. Is there by any chance a PDO mappable object that should be unique be definition, like time, that we could use for this?

2020-04-06 12:17 UTC, Joris-JW submitted a review, later dismissed
I think the chance of false positives is significantly small.

2020-04-06 15:33 UTC, Roelemans commented
The test now also check for current. As Rutger mentioned, it would be ideal if there is a variable in the PDO that always changes, like time. We coincidentally also want to add time to the PDO for encoder data filters, so we will look at that in the future.

2020-04-06 17:47 UTC, RutgerVanBeek submitted a review, later dismissed

2020-04-07 07:39 UTC, RutgerVanBeek approved these changes

2020-04-09 08:36 UTC, Joris-JW approved these changes

2020-04-09 08:36 UTC, merged