Set the elapsed time in the control loop to 4ms minimum
project-march/hardware-interface pull request #254
Opened 2020-04-14 12:46 UTC by Roelemans

Closes PM-401

## Description

Set elapsed_time in the control loop to 4ms minimum. This will remove some peaks in the velocity and make life a bit better. This is a temporary fix until a better solution has been developed.

## Changes

* Set elapsed_time in control loop to 4 sec minimum

2020-04-14 13:09 UTC, Olavhaasie submitted a review, later dismissed

2020-04-14 15:56 UTC, RutgerVanBeek requested changes

2020-04-14 15:56 UTC, RutgerVanBeek commented on march_hardware_interface/src/march_hardware_interface_node.cpp
> +  ros::Duration minimal_elapsed_time = ros::Duration(march.getEthercatCycleTime() / 1000.0);
Shouldn't this be a constant?

2020-04-14 16:21 UTC, RutgerVanBeek approved these changes

2020-04-15 08:36 UTC, Olavhaasie approved these changes

2020-04-23 08:17 UTC, merged