sort joint names alphabetically in yaml
project-march/hardware-interface pull request #265
Opened 2020-05-12 13:58 UTC by RutgerVanBeek

## Description

Lately the sorting of the joints was only done before uploading them to the parameter server (#252). I thought this had no impact, but the joint names are in a different order in the `ImcState.msg` and `AfterLimitJointCommand`. This is a bit unfortunate for the RQT multiplot configurations and the conversion to csv. The easiest was to make sure the joints are used alphabetically again. I tried implementing the sort in the hardware builder, but the happens in place and because of the `unique_ptr` I didn't get it to work. Sorting in the yaml was easier. 
## Changes

* Sort the joint names in the yaml alphabetically

2020-05-14 12:32 UTC, Joris-JW submitted a review, later dismissed
nice.

2020-05-14 13:29 UTC, Ishadijcks requested changes
Requesting changes as this could introduce some hard to find bugs. See comments

Must this also be added to other robots (`march3.yaml`) for compatibility?

2020-05-14 13:29 UTC, Ishadijcks commented on march_hardware_builder/robots/march4.yaml
> +            transmission: 101
Having no new line can break the parsing of YAML files

2020-05-14 13:29 UTC, Ishadijcks commented on march_hardware_builder/robots/march4.yaml
>    joints:
Add a comment here that new joints have to be sorted alphabetically

2020-05-18 07:19 UTC, RutgerVanBeek commented
> Requesting changes as this could introduce some hard to find bugs. See comments
> 
> Must this also be added to other robots (`march3.yaml`) for compatibility?

No, because we have no rqt multiplot configurations for the march3. It is not necessarily that it should be alphabetically, but that is what some (non-essential) things assume, liike the rqt muliplot configurations.

2020-05-18 08:46 UTC, Olavhaasie approved these changes

2020-05-18 09:07 UTC, Joris-JW approved these changes

2020-05-18 09:17 UTC, merged