Use sw file from ems repository
project-march/hardware-interface pull request #267
Opened 2020-05-18 14:07 UTC by Roelemans

Dependent on https://github.com/project-march/ems-projects/pull/1
Closes PM-429

## Description

Get sw files from the ems-projects repo instead of the march_hardware_interface.

2020-05-18 14:51 UTC, RutgerVanBeek submitted a review, later dismissed

2020-05-18 14:57 UTC, Olavhaasie requested changes
you should also remove the `config` directory from `install` command
https://github.com/project-march/hardware-interface/blob/d7f6e83b9f8038b8a5253053e61bbff5f75611b6/march_hardware_builder/CMakeLists.txt#L40

2020-05-20 12:19 UTC, RutgerVanBeek approved these changes
Tested works well, don't forget to push the naming mistake in the ems projects repo

2020-05-20 14:32 UTC, Olavhaasie approved these changes
Good :+1: It would be nice to change the hardcoded package and path to an option the YAML sometime in the future, to avoid having to install the package when writing tests for example.

2020-05-20 14:32 UTC, merged